#!/bin/sh /etc/rc.common

START=99

USE_PROCD=1
NAME=fbw
PROG=/bin/fbw

start_service() {
	procd_open_instance
	procd_set_param command "$PROG"
	procd_close_instance
}

stop() {
	service_stop $PROG
}

reload() {
	service_reload $PROG
}